apps/refunds/urls.py
from .routers import RefundRouter
from .views import RefundsViewSet

router = RefundRouter()

router.register('refunds', RefundsViewSet, basename='refunds')

urlpatterns = router.urls

order_microservice/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, get_resolver

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include([
        path('', include('apps.orders.urls')),
        path('', include('apps.payments.urls')),
        path('', include('apps.webhooks.urls')),
        path('', include('apps.recommendations.urls')),
        path('', include('apps.refunds.urls'))
    ])),
]

apps/refunds/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

from .choices import RefundStatus, ReturnReason
from apps.orders.models import Order


Account = get_user_model()


class Refund(models.Model):
    reason_for_return = models.CharField(max_length=50, choices=ReturnReason.choices)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, to_field="order_uuid")
    user = models.ForeignKey(Account, on_delete=models.CASCADE, to_field='original_id')
    status = models.CharField(max_length=10, choices=RefundStatus.choices, default=RefundStatus.PENDING)
    approval_date = models.DateTimeField(null=True, blank=True)
    rejection_date = models.DateTimeField(null=True, blank=True)
    rejection_reason = models.TextField(blank=True, null=True)

    def approve(self):
        self.status = RefundStatus.APPROVED
        self.approval_date = timezone.now()
        self.save()

    def reject(self, reason):
        self.status = RefundStatus.REJECTED
        self.rejection_date = timezone.now()
        self.rejection_reason = reason
        self.save()

    def __str__(self):
        return f"RefundRequest for Order {self.order_id} - {self.status}"

    class Meta:
        verbose_name = "Refund Request"
        verbose_name_plural = "Refund Requests"

apps/refunds/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .choices import RefundStatus
from .models import Refund

class RefundRequestAdminForm(forms.ModelForm):
    REQUEST_TYPE_CHOICES = [
        ('none', 'None'),  # Default option for no action
        ('approve', 'Approve'),
        ('reject', 'Reject'),
    ]

    request_type = forms.ChoiceField(choices=REQUEST_TYPE_CHOICES, required=False, label='Request Type',)
    rejection_reason = forms.CharField(required=False, widget=forms.Textarea, label='Rejection Reason')

    class Meta:
        model = Refund
        fields = ['reason_for_return', 'order', 'status', 'approval_date', 'user',
                  'rejection_date', 'rejection_reason', 'request_type']

    def clean(self):
        cleaned_data = super().clean()
        request_type = cleaned_data.get('request_type')
        rejection_reason = cleaned_data.get('rejection_reason')
        status = self.instance.status

        if request_type == 'approve' and status != RefundStatus.PENDING:
            raise ValidationError("Only pending requests can be approved.")

        if request_type == 'reject':
            if status != RefundStatus.PENDING:
                raise ValidationError("Only pending requests can be rejected.")
            if not rejection_reason:
                raise ValidationError("Please provide a rejection reason when rejecting a request.")

        return cleaned_data

apps/refunds/views.py
from rest_framework import viewsets, permissions, status
from rest_framework.response import Response

from dependencies.mediator_dependencies.order_processing import get_order_processing_coordinator
from mediators.order_processing_coordinator import OrderProcessingCoordinator
from param_classes.refunds.refund_request_creation import RefundRequestCreationParams
from .serializers.request_body import CreateRefundSerializer


class RefundsViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAuthenticated,)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.order_processing_coordinator: OrderProcessingCoordinator = get_order_processing_coordinator()

    def create_refund_request(self, request, *args, **kwargs) -> Response:
        serializer = CreateRefundSerializer(data={
            "user_id": request.user.id,
            **request.data,
        })
        serializer.is_valid(raise_exception=True)
        refund_creation_params = RefundRequestCreationParams(**serializer.validated_data)
        self.order_processing_coordinator.create_refund_request(refund_creation_params)

        return Response(status=status.HTTP_201_CREATED)

templates/refunds/refund_rejected/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Refund Request Denied - Order #{{ refund.order_id }}</title>
    <style>
        .brandLogo {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .typography {
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
</head>
<body>
    <div>
        <div class="brandLogo" style="margin-bottom: 50px">
            <a href="{{ frontend_url }}">
                <img height="60px" src="https://i.postimg.cc/8cfgL5yS/smile-sales-logo-light-theme.png" alt="Brand Icon">
            </a>
        </div>
        <div>
            <p class="typography">
                Dear, {{ refund.user.first_name }} {{ refund.user.last_name }}
            </p>
            <p class="typography">
                Thank you for contacting us regarding your refund request for order number {{ refund.order_id }}.
                We understand that you requested a refund due to {{ refund.get_reason_for_return_display }}.
            </p>
            <p class="typography">
                We regret to inform you that your refund request has been denied.
                The reason of rejection: {{ refund.rejection_reason }}.
            </p>
            <p class="typography">
                Our return policy outlines the specific conditions for eligible returns and refunds.
                We encourage you to review our policy for more details.
            </p>
            <p class="typography">
                We apologize for any inconvenience this may cause.
                If you have any questions or concerns, please don’t hesitate to contact our customer support team
                at +380-44-123-4567 or smilesalesinfo@example.com.
            </p>
            <p class="typography">
                Sincerely, <br>
                Smile Sales <br>
                Smile Sales customer team
            </p>
        </div>
    </div>
</body>
</html>